t#%%
opimport numpy as np 
import pandas as pd
import pyarrow

## 데이터 불러오기

In [2]:
review_df = pl.read_ndjson("./data/yelp_academic_dataset_review.json")
print(review_df.shape)
review_df.head()

(6990280, 9)

shape: (5, 9)
┌──────────────┬──────────────┬─────────────┬───────┬───┬───────┬──────┬─────────────┬─────────────┐
│ review_id    ┆ user_id      ┆ business_id ┆ stars ┆ … ┆ funny ┆ cool ┆ text        ┆ date        │
│ ---          ┆ ---          ┆ ---         ┆ ---   ┆   ┆ ---   ┆ ---  ┆ ---         ┆ ---         │
│ str          ┆ str          ┆ str         ┆ f64   ┆   ┆ i64   ┆ i64  ┆ str         ┆ str         │
╞══════════════╪══════════════╪═════════════╪═══════╪═══╪═══════╪══════╪═════════════╪═════════════╡
│ KU_O5udG6zpx ┆ mh_-eMZ6K5RL ┆ XQfwVwDr-v0 ┆ 3.0   ┆ … ┆ 0     ┆ 0    ┆ If you      ┆ 2018-07-07  │
│ Og-VcAEodg   ┆ WhZyISBhwA   ┆ ZS3_CbbE5Xw ┆       ┆   ┆       ┆      ┆ decide to   ┆ 22:09:11    │
│              ┆              ┆             ┆       ┆   ┆       ┆      ┆ eat here,   ┆             │
│              ┆              ┆             ┆       ┆   ┆       ┆      ┆ jus…        ┆             │
│ BiTunyQ73aT9 ┆ OyoGAe7OKpv6 ┆ 7ATYjTIgM3j ┆ 5.0   ┆ … ┆ 0     ┆ 1    ┆ I've taken  ┆ 2012-01-03  │
│ WBnpR9DZGw   ┆ SyGZT5g77Q   ┆ Ult4UM3IypQ ┆       ┆   ┆       ┆      ┆ a lot of    ┆ 15:28:18    │
│              ┆              ┆             ┆       ┆   ┆       ┆      ┆ spin class… ┆             │
│ saUsX_uimxRl ┆ 8g_iMtfSiwik ┆ YjUWPpI6HXG ┆ 3.0   ┆ … ┆ 0     ┆ 0    ┆ Family      ┆ 2014-02-05  │
│ CVr67Z4Jig   ┆ VnbP2etR0A   ┆ 530lwP-fb2A ┆       ┆   ┆       ┆      ┆ diner. Had  ┆ 20:30:30    │
│              ┆              ┆             ┆       ┆   ┆       ┆      ┆ the buffet. ┆             │
│              ┆              ┆             ┆       ┆   ┆       ┆      ┆ …           ┆             │
│ AqPFMleE6RsU ┆ _7bHUi9Uuf5_ ┆ kxX2SOes4o- ┆ 5.0   ┆ … ┆ 0     ┆ 1    ┆ Wow!        ┆ 2015-01-04  │
│ 23_auESxiA   ┆ _HHc_Q8guQ   ┆ D3ZQBkiMRfA ┆       ┆   ┆       ┆      ┆ Yummy,      ┆ 00:01:03    │
│              ┆              ┆             ┆       ┆   ┆       ┆      ┆ different,  ┆             │
│              ┆              ┆             ┆       ┆   ┆       ┆      ┆ delic…      ┆             │
│ Sx8TMOWLNuJB ┆ bcjbaE6dDog4 ┆ e4Vwtrqf-wp ┆ 4.0   ┆ … ┆ 0     ┆ 1    ┆ Cute        ┆ 2017-01-14  │
│ Wer-0pcmoA   ┆ jkNY91ncLQ   ┆ JfwesgvdgxQ ┆       ┆   ┆       ┆      ┆ interior    ┆ 20:54:15    │
│              ┆              ┆             ┆       ┆   ┆       ┆      ┆ and owner   ┆             │
│              ┆              ┆             ┆       ┆   ┆       ┆      ┆ (?) ga…     ┆             │
└──────────────┴──────────────┴─────────────┴───────┴───┴───────┴──────┴─────────────┴─────────────┘

In [3]:
review_df = review_df.to_pandas()
review_df = review_df.sample(n=100000)
print(review_df.shape)
review_df.head()

(100000, 9)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
6083244,ARrnaYXres6UWd8HafjnJA,4Q4EqGJIyUSWg-WZ1y4fvQ,mjOmgTps0-zZ8DfmJO3iAg,2.0,2,0,0,"So.... it's the new thing, right? Service is S...",2019-12-24 02:53:41
3765012,Pt4eKPZ5BiNp8Bi-TLXSlQ,3YdxNc-3GaoXi4TfUGes_Q,7J4k_kJN32LEQ6ibixj7wg,4.0,0,0,0,"Steaks weren't bad, when they say they use che...",2015-04-12 01:29:02
642376,VaKhFnGxTQRn2StjoekUMg,mJx8CSu0SfLMIlMW0300vg,OpXFFEDRXj-JakazHvxY9Q,5.0,0,0,0,Went to Outsiders on the recommendation of a b...,2020-08-23 20:40:27
3545743,S31azXBRewWmvTiBk4s2wA,nC9JvVz7UCvcDBMqM7kOdg,YV83252nBml7BmQLdAniYg,4.0,0,0,0,I'm going to start by saying that I rounded-up...,2013-05-09 17:59:29
5268285,SfPS_9WzLaCN_q7zfBxECw,SxHODD3vrIB0rpsC_NiYGg,5srKt6H8Y1Ko80hboucZEg,5.0,0,0,0,My family loves going to sushi club. Great va...,2019-02-09 18:32:02

## 리뷰 데이터 전처리 -> 특정 가게로 한정하기

In [16]:
## 특정 가게 중 리뷰가 많은 가게를 하나 임의 선택
sample_business_id = review_df['business_id'].value_counts().reset_index().iloc[0,0]
print("sample_business_id: ", sample_business_id)

sample_business_id:  _ab50qdWOk0DdB6XOrBitw

In [40]:
sample_df = review_df[review_df['business_id'] == sample_business_id]
print(sample_df.shape)
sample_df.head()

(115, 9)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
5002708,g_bBPTO8DqAbg3ISoxflTg,wweJxy_n604PUrA_7IRMTw,_ab50qdWOk0DdB6XOrBitw,5.0,0,0,0,"Excellence in flavor and service, ACME has eve...",2015-02-06 21:17:27
5449778,fO81hXadtSqXV2cfYWhP6A,fIYB_hCgLZx96Ha0hY1caQ,_ab50qdWOk0DdB6XOrBitw,4.0,1,0,0,"Was in NOLA las month, dropped in the first ni...",2020-03-11 21:48:41
5111363,6xO4aNSYyi0RKl9f3nqVYg,R1zGFXnbsNsm1nHirq4WoQ,_ab50qdWOk0DdB6XOrBitw,5.0,0,0,0,This hands down has to be the best place to ge...,2017-04-27 23:41:59
5147319,mPtcBs9qOfFZoYy5JpjDvw,25T3g5ml8w4zqq-npCZ0TA,_ab50qdWOk0DdB6XOrBitw,2.0,0,0,0,We only came here because of the chargrilled o...,2017-03-02 15:11:59
5018900,JjxKhTtilET6Bo99YTeHRw,hXSzBUjnORNXkaxwA1j-vg,_ab50qdWOk0DdB6XOrBitw,4.0,5,2,3,ACME Oyster House is a seafood house near Bour...,2013-11-05 21:37:04

## 리뷰 데이터 전처리 -> Text 데이터 전처리

In [46]:
#Sample Df의 Text Column을 "."를 기준으로 나눈다음, review_id,"."로 나눠진 text로 이루어진 DataFrame을 만든다. 
explode_df  = sample_df['text'].str.split(".").explode()
explode_df  = sample_df[['review_id']].join(explode_df)
explode_df = explode_df[explode_df['text'] != ""] # 빈 문자열 제거
explode_df['text'] = explode_df['text'].str.replace("\n", " ").str.replace("\t", " ").str.replace("\r", " ")
print(explode_df.shape)
explode_df.head()

(766, 2)

,review_id,text
5002708,g_bBPTO8DqAbg3ISoxflTg,"Excellence in flavor and service, ACME has eve..."
5002708,g_bBPTO8DqAbg3ISoxflTg,"Sitting at the oyster bar, you can enjoy the..."
5002708,g_bBPTO8DqAbg3ISoxflTg,"""Stormin"" Norman and has buddy Devin are the ..."
5002708,g_bBPTO8DqAbg3ISoxflTg,Great food and super service make ACME a must...
5449778,fO81hXadtSqXV2cfYWhP6A,"Was in NOLA las month, dropped in the first ni..."

## Bertopic을 이용한 Topic Modeling

In [42]:
!pip install bertopic

Collecting bertopic
  Downloading bertopic-0.16.3-py3-none-any.whl.metadata (23 kB)
Collecting hdbscan>=0.8.29 (from bertopic)
  Downloading hdbscan-0.8.37-cp311-cp311-macosx_10_9_universal2.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.20.0 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from bertopic) (1.26.4)
Requirement already satisfied: pandas>=1.1.5 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from bertopic) (2.2.2)
Collecting plotly>=4.7.0 (from bertopic)
  Downloading plotly-5.23.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scikit-learn>=0.22.2.post1 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from bertopic) (1.5.0)
Collecting sentence-transformers>=0.4.1 (from bertopic)
  Downloading sentence_transformers-3.0.1-py3-none-any.whl.metadata (10 kB)
Collecting tqdm>=4.41.1 (from bertopic)
  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
Collecting umap-learn>=0.5.0 (from bertopic)
  Downloading umap_learn-0.5.6-py3-none-any.whl.metadata (21 kB)
Collecting cython<3,>=0.27 (from hdbscan>=0.8.29->bertopic)
  Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: scipy>=1.0 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from hdbscan>=0.8.29->bertopic) (1.10.1)
Requirement already satisfied: joblib>=1.0 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from hdbscan>=0.8.29->bertopic) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from pandas>=1.1.5->bertopic) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from pandas>=1.1.5->bertopic) (2024.1)
Collecting tenacity>=6.2.0 (from plotly>=4.7.0->bertopic)
  Downloading tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: packaging in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from plotly>=4.7.0->bertopic) (23.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from scikit-learn>=0.22.2.post1->bertopic) (3.5.0)
Collecting transformers<5.0.0,>=4.34.0 (from sentence-transformers>=0.4.1->bertopic)
  Downloading transformers-4.43.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 4.0 MB/s eta 0:00:00
Requirement already satisfied: torch>=1.11.0 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from sentence-transformers>=0.4.1->bertopic) (2.3.1)
Collecting huggingface-hub>=0.15.1 (from sentence-transformers>=0.4.1->bertopic)
  Downloading huggingface_hub-0.24.5-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: Pillow in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from sentence-transformers>=0.4.1->bertopic) (10.3.0)
Collecting numba>=0.51.2 (from umap-learn>=0.5.0->bertopic)
  Downloading numba-0.60.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting pynndescent>=0.5 (from umap-learn>=0.5.0->bertopic)
  Downloading pynndescent-0.5.13-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: filelock in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (3.15.1)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2024.6.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (6.0.1)
Requirement already satisfied: requests in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2.32.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (4.11.0)
Collecting llvmlite<0.44,>=0.43.0dev0 (from numba>=0.51.2->umap-learn>=0.5.0->bertopic)
  Downloading llvmlite-0.43.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (4.8 kB)
Requirement already satisfied: six>=1.5 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.16.0)
Requirement already satisfied: sympy in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.12.1)
Requirement already satisfied: networkx in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.3)
Requirement already satisfied: jinja2 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.4)
Collecting regex!=2019.12.17 (from transformers<5.0.0,>=4.34.0->sentence-transformers>=0.4.1->bertopic)
  Downloading regex-2024.7.24-cp311-cp311-macosx_11_0_arm64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 4.4 MB/s eta 0:00:00
Collecting safetensors>=0.4.1 (from transformers<5.0.0,>=4.34.0->sentence-transformers>=0.4.1->bertopic)
  Downloading safetensors-0.4.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (3.8 kB)
Collecting tokenizers<0.20,>=0.19 (from transformers<5.0.0,>=4.34.0->sentence-transformers>=0.4.1->bertopic)
  Downloading tokenizers-0.19.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.7 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2024.2.2)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /Users/bono/miniconda3/envs/ASAC_5th/lib/python3.11/site-packages (from sympy->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Downloading bertopic-0.16.3-py3-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 10.5 MB/s eta 0:00:00
Downloading hdbscan-0.8.37-cp311-cp311-macosx_10_9_universal2.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 10.4 MB/s eta 0:00:00a 0:00:01
Downloading plotly-5.23.0-py3-none-any.whl (17.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 9.7 MB/s eta 0:00:0000:0100:01m
Downloading sentence_transformers-3.0.1-py3-none-any.whl (227 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 10.0 MB/s eta 0:00:00
Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Downloading umap_learn-0.5.6-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 7.9 MB/s eta 0:00:00
Using cached Cython-0.29.37-py2.py3-none-any.whl (989 kB)
Downloading huggingface_hub-0.24.5-py3-none-any.whl (417 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.5/417.5 kB 7.3 MB/s eta 0:00:00ta 0:00:01
Downloading numba-0.60.0-cp311-cp311-macosx_11_0_arm64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 11.9 MB/s eta 0:00:0000:0100:01
Downloading pynndescent-0.5.13-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.9/56.9 kB 5.1 MB/s eta 0:00:00
Downloading tenacity-9.0.0-py3-none-any.whl (28 kB)
Downloading transformers-4.43.3-py3-none-any.whl (9.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 12.1 MB/s eta 0:00:0000:0100:01
Downloading llvmlite-0.43.0-cp311-cp311-macosx_11_0_arm64.whl (28.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.8/28.8 MB 11.5 MB/s eta 0:00:0000:0100:01
Downloading regex-2024.7.24-cp311-cp311-macosx_11_0_arm64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.9/278.9 kB 12.6 MB/s eta 0:00:00
Downloading safetensors-0.4.3-cp311-cp311-macosx_11_0_arm64.whl (410 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.3/410.3 kB 10.6 MB/s eta 0:00:0000:01
Downloading tokenizers-0.19.1-cp311-cp311-macosx_11_0_arm64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 11.4 MB/s eta 0:00:00a 0:00:01
Installing collected packages: tqdm, tenacity, safetensors, regex, llvmlite, cython, plotly, numba, huggingface-hub, tokenizers, pynndescent, hdbscan, umap-learn, transformers, sentence-transformers, bertopic
Successfully installed bertopic-0.16.3 cython-0.29.37 hdbscan-0.8.37 huggingface-hub-0.24.5 llvmlite-0.43.0 numba-0.60.0 plotly-5.23.0 pynndescent-0.5.13 regex-2024.7.24 safetensors-0.4.3 sentence-transformers-3.0.1 tenacity-9.0.0 tokenizers-0.19.1 tqdm-4.66.4 transformers-4.43.3 umap-learn-0.5.6

In [43]:
from bertopic import BERTopic

In [47]:
docs = explode_df['text'].tolist()
docs[:2]

['Excellence in flavor and service, ACME has everything a true foodie desires',
 '  Sitting at the oyster bar, you can enjoy the shuckers prepare their signature dish, the charbroiled oysters']

In [72]:
topic_model = BERTopic(language="english", nr_topics=3 ,calculate_probabilities=True, verbose=True) #4로 한 것은 outlier topic을 포함한 것이다.
topics, probs = topic_model.fit_transform(docs)

2024-08-01 21:07:39,817 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/24 [00:00<?, ?it/s]

2024-08-01 21:07:42,898 - BERTopic - Embedding - Completed ✓
2024-08-01 21:07:42,899 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-08-01 21:07:44,470 - BERTopic - Dimensionality - Completed ✓
2024-08-01 21:07:44,471 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-08-01 21:07:44,502 - BERTopic - Cluster - Completed ✓
2024-08-01 21:07:44,503 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-08-01 21:07:44,520 - BERTopic - Representation - Completed ✓
2024-08-01 21:07:44,520 - BERTopic - Topic reduction - Reducing number of topics
2024-08-01 21:07:44,540 - BERTopic - Topic reduction - Reduced number of topics from 14 to 3

In [73]:
len(probs),len(docs), topic_model.get_topic_info()['Count'].sum()

(766, 766, 766)

In [74]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,195,-1_the_and_to_of,"[the, and, to, of, was, we, it, in, for, that]","[ Watching these guys work is awesome, plus it makes you hungry! LOL! But even on the few occasions, I'm seated at a table, the interactions with the wait staff are always fun! I guess it's part of that New Orleans spirit! I mainly come here for the oysters and Po Boys and every visit you are sure to get fresh seafood and piles of it, My food was great howveer the service was HORRIBLE! First we stood outside in the freezing cold (on the coldest night in NOLA) only to go inside and find that there were tables in the back where no one was that we could have been seated at, The oysters are chargrilled with butter, garlic, and parmesan cheese, and they were so good! For dessert, go with the banana foster cheesecake - amazing!! We got here at 6pm on a Sunday with a party of 6 and we had to wait an hour to get in! I wouldn't skip out on this place because of the wait, I would just plan to go for a late lunch or early dinner instead]"
1,0,544,0_the_and_oysters_was,"[the, and, oysters, was, to, in, it, of, we, but]","[ The raw oysters are a must, but you should try these, the light char on the oyster and that butter sauce is OMG!! Roast Beef Po Boy - This is totally a New Orleans' thing, but you have to do this, This hands down has to be the best place to get oysters in New Orleans! It was so highly recommended by a few people that have been and they all let me know that I must try the chargrilled oysters, The line was long it took us about 45 mins to get seated but it was by far worth the wait in line! Michael our Shucker/ Server was great had worked for Acme for 35 years!!!! The oysters were delicious!! Service fast with happy faces all around!!! Definitely hit this spot if you're in for a good meal in NOLA]"
2,1,27,1_star_stars_will_be,"[star, stars, will, be, back, ill, food, definitely, return, can]","[ 1/2 Star, Each Category can be given up to 1 star except food (2 stars) because I consider all these categories important to the overall dining experience, 1 Star - Will I come back? - If I know for a fact I'll return, I'll give this a star]"

In [98]:
# topics를 explode_df에 추가
explode_df['topic'] = topics
explode_df.head(30)

,review_id,text,topic
5276764,093fRyxgwsilVBpxFw97YQ,The hush puppies the fish them damn char oysters heaven,0
5276764,093fRyxgwsilVBpxFw97YQ,Loved it i will be be returning honey omg,0
5441823,0G7ekwLU1Wo32hbjIDPh9A,"There was a little bit of a wait and the restaurant was filled with people, but you don't even notice or care once you start eating",-1
5441823,0G7ekwLU1Wo32hbjIDPh9A,"I am an oyster lover 100%!!!! Always have been and will always be! I've had them made so many different ways, but the chargrilled oysters from Acme Oyster House is definitely one of my top 3 all time favorites! Soooooooo delicious! Soooooo fresh! And no joke",0
5441823,0G7ekwLU1Wo32hbjIDPh9A,you won't be able to stop eating them once you start! Between 4 people we had 5 dozen! The fresh oysters were amazing too,-1
5441823,0G7ekwLU1Wo32hbjIDPh9A,but there was just something special about those chargrilled oysters,-1
5441823,0G7ekwLU1Wo32hbjIDPh9A,The staff was extremely friendly & helpful when giving drink suggestions,-1
5441823,0G7ekwLU1Wo32hbjIDPh9A,And our food came out quickly,-1
5441823,0G7ekwLU1Wo32hbjIDPh9A,every single time we put in another order for more oysters lol,0
5441823,0G7ekwLU1Wo32hbjIDPh9A,If you are in New Orleans you have to stop by this place!!!!,0
4933897,1-Y_X_R7j4G3E1C-oYjXIw,We ate here a few days ago,-1
4933897,1-Y_X_R7j4G3E1C-oYjXIw,The food was amazing,0
4933897,1-Y_X_R7j4G3E1C-oYjXIw,"I got the 1/2 and 1/2 fish and shrimp po boy, it was great, give it a try",0
4891104,1fquUTAXhsgm-Gh__bcb8Q,"The line was very long, but it moved very quickly",0
4891104,1fquUTAXhsgm-Gh__bcb8Q,We sat at the bar,0
4891104,1fquUTAXhsgm-Gh__bcb8Q,"The raw oysters were really good and plump! The charbroiled oysters were very decadent, but delicious",0
4891104,1fquUTAXhsgm-Gh__bcb8Q,"I think they were too heavy for me though, so I'll stick to the raw oysters next time",0
4891104,1fquUTAXhsgm-Gh__bcb8Q,"The craw puppies were tasty, with a kick to them",0
4891104,1fquUTAXhsgm-Gh__bcb8Q,"The jambalaya was excellent! Our server, Pam, was very friendly and helpful",0
5118539,1tvU0aAol3iBnEj92wbGZQ,"Got here when there was no line,food came out fast and hot and DELISCIOUS! Meat pies sorta like minature empanadas they were very good,of course ordered oysters raw and baked and they were deliscious a must try if you like oysters",0
5118539,1tvU0aAol3iBnEj92wbGZQ,fried crawfish was very good and the bread pudding was the best i ever had!,0
5068050,2QtSiQwNAA6QVRcpPUicSw,One of the guys told me he handles about 900 oysters a day and they are busy from start to finish,0
5068050,2QtSiQwNAA6QVRcpPUicSw,This place was great,0
5068050,2QtSiQwNAA6QVRcpPUicSw,Everyone was so friendly,0
5068050,2QtSiQwNAA6QVRcpPUicSw,It was awesome,0
5068050,2QtSiQwNAA6QVRcpPUicSw,The fried fish po boy was great,1
5302553,2gusI_duQTfcfN_4J3DXRQ,We were at Harrahs Casino and decided to eat there,0
5302553,2gusI_duQTfcfN_4J3DXRQ,The food was good but the service was deplorable,0
5302553,2gusI_duQTfcfN_4J3DXRQ,The seafood platter was cooked really well the char grilled oysters were ok nothing to rave about,0
5302553,2gusI_duQTfcfN_4J3DXRQ,They even charged for a glass of water,0

## 리뷰 별 토픽 리스트업, -1은 제거하였음

In [124]:
# topic_df = explode_df.groupby('review_id')['topic'].apply(lambda x: list(set(x.tolist()))).reset_index()
topic_df = explode_df.groupby('review_id')['topic'].apply(lambda x: [item for item in set(x.tolist()) if item != -1]).reset_index()

# 이 때 topic 컬럼의 리스트 값을 오름차순으로 정렬한다.
topic_df['topic'] = topic_df['topic'].apply(lambda x: sorted(x))
print(topic_df.shape)
topic_df.head()

(115, 2)

                review_id topic
0  093fRyxgwsilVBpxFw97YQ   [0]
1  0G7ekwLU1Wo32hbjIDPh9A   [0]
2  1-Y_X_R7j4G3E1C-oYjXIw   [0]
3  1fquUTAXhsgm-Gh__bcb8Q   [0]
4  1tvU0aAol3iBnEj92wbGZQ   [0]

In [121]:
import pandas as pd
topic_df = pd.DataFrame(topic_df['topic'].values.tolist()).add_prefix('topic_').join(topic_df)
print(topic_df.shape)
topic_df.head()

(115, 4)

   topic_0  topic_1               review_id topic
0      0.0      NaN  093fRyxgwsilVBpxFw97YQ   [0]
1      0.0      NaN  0G7ekwLU1Wo32hbjIDPh9A   [0]
2      0.0      NaN  1-Y_X_R7j4G3E1C-oYjXIw   [0]
3      0.0      NaN  1fquUTAXhsgm-Gh__bcb8Q   [0]
4      0.0      NaN  1tvU0aAol3iBnEj92wbGZQ   [0]

## 리뷰별 특정 토픽 여부를 컬럼으로 분류하여 표기

In [122]:
import numpy as np
# topic_df의 topic_0 ~ topic_2까지 확인해서 nan이면 0 아니면 1로 변경하기
topic_df.iloc[:, :2] = np.where(topic_df.iloc[:, :2].isnull(), 0, 1)

In [123]:
topic_df

     topic_0  topic_1               review_id topic
0        1.0      0.0  093fRyxgwsilVBpxFw97YQ   [0]
1        1.0      0.0  0G7ekwLU1Wo32hbjIDPh9A   [0]
2        1.0      0.0  1-Y_X_R7j4G3E1C-oYjXIw   [0]
3        1.0      0.0  1fquUTAXhsgm-Gh__bcb8Q   [0]
4        1.0      0.0  1tvU0aAol3iBnEj92wbGZQ   [0]
..       ...      ...                     ...   ...
110      1.0      0.0  yX_vbx9TL5JRY8cmraKjag   [0]
111      1.0      0.0  z7T_Eegjmz9sofPTZZUhmg   [0]
112      1.0      0.0  zcdl-3Kf6AWuKakr8cQQ6Q   [0]
113      1.0      0.0  zeIQHj-VwHbGAzGZVauyIQ   [0]
114      1.0      0.0  zgrZpY_wDtAElUs9QYupYw   [0]

[115 rows x 4 columns]